services:
  auction.webapi:
    env_file: ".env"
    image: ${DOCKER_REGISTRY-}auctionwebapi
    container_name: auction.webapi
    networks:
        - main
    ports:
      - "${WAKEUP_SERVICES_HTTP_PORT:-1180}:${WAKEUP_SERVICES_HTTP_PORT:-8080}"
    build:
      context: .
      dockerfile: Auction.WebApi/Dockerfile
    depends_on:
        - auction.database
        - auction.redis

  auction.database:
    image: postgres
    container_name: auction.db
    ports:
        - "5432:5432"
    volumes:
        - db:/auction/db
    networks:
        - main
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}

  auction.redis:
    image: redis:latest
    container_name: auction.redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/auction/redis
    networks:
      - main
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: petruho@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
    ports:
    - "15432:80"
    volumes:
    - pgAdmin:/auction/pgadmin
    networks:
    - main
    depends_on:
    - auction.database



networks:
  main: 
    driver: bridge

volumes:
  webapi:
  db:
  redis:
  pgAdmin:
      
